version: 2

updates:

  - package-ecosystem: "docker"
    directories:
      - "/*"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "CCM-9336: "
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directories:
      - "/*"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "CCM-9336: "
    cooldown:
      default-days: 7

  - package-ecosystem: "npm"
    directories:
      - "/*"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "CCM-9336: "
    cooldown:
      default-days: 7

  - package-ecosystem: "pip"
    directories:
      - "/*"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "CCM-9336: "
    cooldown:
      default-days: 7

  - package-ecosystem: "terraform"
    directories:
      - "/*"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "CCM-9336: "
    cooldown:
      default-days: 7
