#!/usr/bin/env bash

# WARNING: Please DO NOT edit this file! It is maintained in the Repository Template (https://github.com/nhs-england-tools/repository-template). Raise a PR instead.

set -euo pipefail

# Run tfsec for security checks on Terraform code.
#
# Usage:
#   $ ./tfsec.sh [directory]
# ==============================================================================

function main() {

  cd "$(git rev-parse --show-toplevel)"

  local dir_to_scan=${1:-.}
  run-tfsec "$dir_to_scan"
}

# Run tfsec on the specified directory.
# Arguments:
#   $1 - Directory to scan
function run-tfsec() {

  local dir_to_scan="$1"

  if ! command -v tfsec &> /dev/null; then
    echo "tfsec could not be found, please install it first."
    exit 1
  fi

  echo "Running tfsec on directory: $dir_to_scan"
  tfsec \
    --concise-output \
    --force-all-dirs \
    --exclude-downloaded-modules \
    --config-file ../config/tfsec.yaml \
    "$dir_to_scan"

  check-tfsec-status
}

# Check the exit status of tfsec.
function check-tfsec-status() {

  if [ $? -eq 0 ]; then
    echo "TFSec completed successfully."
  else
    echo "TFSec found issues."
    exit 1
  fi
}

# ==============================================================================

main "$@"

exit 0
